import 'package:data_connection_checker/data_connection_checker.dart';
import 'package:dio/dio.dart';
import 'package:flutter_ui_kit/academy/data/repository/course_repo.dart';
import 'package:flutter_ui_kit/academy/data/repository/payment_repo.dart';
import 'package:flutter_ui_kit/academy/provider/course_provider.dart';
import 'package:flutter_ui_kit/academy/provider/payment_provider.dart';
import 'package:flutter_ui_kit/dating_app/data/repository/choice_repo.dart';
import 'package:flutter_ui_kit/dating_app/data/repository/dating_app_chat_repo.dart';
import 'package:flutter_ui_kit/dating_app/data/repository/dating_app_home_repo.dart';
import 'package:flutter_ui_kit/dating_app/data/repository/dating_app_profile_repo.dart';
import 'package:flutter_ui_kit/dating_app/data/repository/dating_app_user_repo.dart';
import 'package:flutter_ui_kit/dating_app/data/repository/datingapp_notification_repo.dart';
import 'package:flutter_ui_kit/dating_app/data/repository/datingapp_onboarding_repo.dart';
import 'package:flutter_ui_kit/dating_app/provider/choice_provider.dart';
import 'package:flutter_ui_kit/dating_app/provider/dating_app_chat_Provider.dart';
import 'package:flutter_ui_kit/dating_app/provider/dating_app_home_provider.dart';
import 'package:flutter_ui_kit/dating_app/provider/dating_app_onboarding_provider.dart';
import 'package:flutter_ui_kit/dating_app/provider/dating_app_user_provider.dart';
import 'package:flutter_ui_kit/dating_app/provider/dattingapp_notification_provider.dart';
import 'package:flutter_ui_kit/dating_app/provider/profile_provider.dart';
import 'package:flutter_ui_kit/doctor/data/datasource/remote/dio/dio_client.dart';
import 'package:flutter_ui_kit/doctor/data/datasource/remote/dio/logging_interceptor.dart';
import 'package:flutter_ui_kit/doctor/data/repository/appointment_repo.dart';
import 'package:flutter_ui_kit/doctor/data/repository/auth_repo.dart';
import 'package:flutter_ui_kit/doctor/data/repository/onboarding_repo.dart';
import 'package:flutter_ui_kit/doctor/data/repository/profile_repo.dart';
import 'package:flutter_ui_kit/doctor/data/repository/chat_repo.dart';
import 'package:flutter_ui_kit/doctor/data/repository/contact_repo.dart';
import 'package:flutter_ui_kit/doctor/data/repository/faq_repo.dart';
import 'package:flutter_ui_kit/doctor/data/repository/membership_repo.dart';
import 'package:flutter_ui_kit/doctor/helper/network_info.dart';
import 'package:flutter_ui_kit/doctor/provider/appointment_provider.dart';
import 'package:flutter_ui_kit/doctor/provider/auth_provider.dart';
import 'package:flutter_ui_kit/doctor/provider/onboarding_provider.dart';
import 'package:flutter_ui_kit/doctor/provider/profile_provider.dart';
import 'package:flutter_ui_kit/doctor/provider/chat_provider.dart';
import 'package:flutter_ui_kit/doctor/provider/contact_provider.dart';
import 'package:flutter_ui_kit/doctor/provider/faq_provider.dart';
import 'package:flutter_ui_kit/doctor/utility/app_constants.dart';
import 'package:flutter_ui_kit/driver_app/data/repository/driverapp_home_repo.dart';
import 'package:flutter_ui_kit/driver_app/data/repository/driverapp_onboarding_repo.dart';
import 'package:flutter_ui_kit/driver_app/data/repository/history_repo.dart';
import 'package:flutter_ui_kit/driver_app/data/repository/notification_repo.dart';
import 'package:flutter_ui_kit/driver_app/data/repository/payment_repo.dart';
import 'package:flutter_ui_kit/driver_app/provider/destination_provider.dart';
import 'package:flutter_ui_kit/driver_app/provider/driverapp_auth_provider.dart';
import 'package:flutter_ui_kit/driver_app/provider/driverapp_home_provider.dart';
import 'package:flutter_ui_kit/driver_app/provider/driverapp_onboarding_provider.dart';
import 'package:flutter_ui_kit/driver_app/provider/history_provider.dart';
import 'package:flutter_ui_kit/driver_app/provider/notification_provider.dart';
import 'package:flutter_ui_kit/driver_app/provider/payment_provider.dart';
import 'package:flutter_ui_kit/food/provider/home_provider.dart';
import 'package:flutter_ui_kit/grocery/data/repository/branch_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/cart_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/checkout_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/choose_category_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/favourite_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/home_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/onboarding_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/payment_repo.dart';
import 'package:flutter_ui_kit/grocery/data/repository/search_repo.dart';
import 'package:flutter_ui_kit/grocery/provider/branch_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/cart_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/checkout_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/choose_category_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/favourite_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/home_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/onboarding_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/payment_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/product_provider.dart';
import 'package:flutter_ui_kit/grocery/provider/search_provider.dart';
import 'package:flutter_ui_kit/household_app/data/repository/service_repo.dart';
import 'package:flutter_ui_kit/household_app/provider/service_provider.dart';
import 'package:flutter_ui_kit/household_app/data/repository/home_repo.dart';
import 'package:flutter_ui_kit/household_app/provider/house_home_provider.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/banner_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/cart_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/category_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/chat_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/coupon_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/language_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/location_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/notification_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/onboarding_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/order_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/product_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/profile_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/search_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/set_menu_repo.dart';
import 'package:flutter_ui_kit/restaurant/data/repository/wishlist_repo.dart';
import 'package:flutter_ui_kit/restaurant/provider/auth_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/banner_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/cart_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/category_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/chat_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/coupon_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/language_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/localization_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/location_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/notification_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/onboarding_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/order_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/product_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/profile_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/search_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/set_menu_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/theme_provider.dart';
import 'package:flutter_ui_kit/restaurant/provider/wishlist_provider.dart';

import 'package:flutter_ui_kit/restaurant_delivery_boy/data/repository/auth_repo.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/data/repository/language_repo.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/data/repository/order_repo.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/data/repository/profile_repo.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/data/repository/splash_repo.dart';

import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/auth_provider.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/language_provider.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/localization_provider.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/location_provider.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/order_provider.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/profile_provider.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/splash_provider.dart';
import 'package:flutter_ui_kit/restaurant_delivery_boy/provider/theme_provider.dart';

import 'package:flutter_ui_kit/rideshare/data/repository/destination_repo.dart';
import 'package:flutter_ui_kit/rideshare/data/repository/history_repo.dart';
import 'package:flutter_ui_kit/rideshare/data/repository/notification_repo.dart';
import 'package:flutter_ui_kit/rideshare/data/repository/rideshare_home_repo.dart';
import 'package:flutter_ui_kit/rideshare/data/repository/rideshare_onboarding_repo.dart';
import 'package:flutter_ui_kit/rideshare/data/repository/wallet_repo.dart';
import 'package:flutter_ui_kit/rideshare/provider/rideshare_destination_provider.dart';
import 'package:flutter_ui_kit/rideshare/provider/history_provider.dart';
import 'package:flutter_ui_kit/rideshare/provider/notification_provider.dart';
import 'package:flutter_ui_kit/rideshare/provider/rideshare_auth_provider.dart';
import 'package:flutter_ui_kit/rideshare/provider/rideshare_home_provider.dart';
import 'package:flutter_ui_kit/rideshare/provider/rideshare_onboarding_provider.dart';
import 'package:flutter_ui_kit/rideshare/provider/wallet_provider.dart';
import 'package:flutter_ui_kit/screens/provider/auth_provider.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/auth_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/banner_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/brand_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/cart_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/category_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/chat_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/coupon_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/mega_deal_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/notification_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/onboarding_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/order_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/product_details_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/product_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/profile_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/search_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/seller_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/splash_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/support_ticket_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/tracking_repo.dart';
import 'package:flutter_ui_kit/sixvalley/data/repository/wishlist_repo.dart';
import 'package:flutter_ui_kit/sixvalley/provider/auth_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/banner_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/brand_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/cart_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/category_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/chat_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/coupon_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/localization_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/mega_deal_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/notification_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/onboarding_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/order_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/product_details_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/product_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/profile_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/search_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/seller_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/splash_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/support_ticket_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/theme_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/tracking_provider.dart';
import 'package:flutter_ui_kit/sixvalley/provider/wishlist_provider.dart';
import 'package:flutter_ui_kit/wallet/data/repository/charity_repo.dart';
import 'package:flutter_ui_kit/wallet/data/repository/gift_repo.dart';
import 'package:flutter_ui_kit/wallet/data/repository/goals_repo.dart';
import 'package:flutter_ui_kit/wallet/data/repository/organization_repo.dart';
import 'package:flutter_ui_kit/wallet/data/repository/promo_repo.dart';
import 'package:flutter_ui_kit/wallet/provider/charity_provider.dart';
import 'package:flutter_ui_kit/wallet/provider/gift_provider.dart';
import 'package:flutter_ui_kit/wallet/provider/goals_provider.dart';
import 'package:flutter_ui_kit/wallet/provider/organization_provider.dart';
import 'package:flutter_ui_kit/wallet/data/repository/step_repo.dart';
import 'package:flutter_ui_kit/wallet/provider/promo_provider.dart';
import 'package:flutter_ui_kit/wallet/provider/step_provider.dart';
import 'package:flutter_ui_kit/household_app/provider/notification_provider.dart';
import 'package:flutter_ui_kit/household_app/data/repository/notification_repo.dart';
import 'package:flutter_ui_kit/household_app/provider/cart_provider.dart';
import 'package:flutter_ui_kit/academy/provider/wish_list_provider.dart';
import 'package:flutter_ui_kit/academy/provider/design_provider.dart';
import 'package:flutter_ui_kit/academy/data/repository/wish_list_repo.dart';
import 'package:flutter_ui_kit/academy/data/repository/design_repo.dart';
import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter_ui_kit/main/main_provider.dart';
import 'doctor/provider/membership_provider.dart';

final sl = GetIt.instance;

Future<void> init() async {
  // Core
  sl.registerLazySingleton(() => NetworkInfo(sl()));
  sl.registerLazySingleton(
      () => DioClient(AppConstants.BASE_URL, sl(), loggingInterceptor: sl()));

  // Repository
  sl.registerLazySingleton(() => OnBoardingRepo());
  sl.registerLazySingleton(() => AuthRepo());
  sl.registerLazySingleton(() => ProfileRepo());
  sl.registerLazySingleton(() => MembershipRepo());
  sl.registerLazySingleton(() => ChatRepo());
  sl.registerLazySingleton(() => ContactRepo());
  sl.registerLazySingleton(() => FaqRepo());
  sl.registerLazySingleton(() => StepRepo());
  sl.registerLazySingleton(() => CharityRepo());
  sl.registerLazySingleton(() => OrganizationRepo());
  sl.registerLazySingleton(() => GiftRepo());
  sl.registerLazySingleton(() => GoalsRepo());
  sl.registerLazySingleton(() => PromoRepo());
  sl.registerLazySingleton(() => AppointmentRepo());
  sl.registerLazySingleton(() => OnboardingRepo());
  sl.registerLazySingleton(() => ChooseCategoryRepo());
  sl.registerLazySingleton(() => HomeRepo());
  sl.registerLazySingleton(() => SearchRepo());
  sl.registerLazySingleton(() => BranchRepo());
  sl.registerLazySingleton(() => CartRepo());
  sl.registerLazySingleton(() => CheckoutRepo());
  sl.registerLazySingleton(() => FavouriteRepo());
  sl.registerLazySingleton(() => PaymentRepo());
  sl.registerLazySingleton(() => RideShareOnBoardingRepo());
  sl.registerLazySingleton(() => RideShareHomeRepo());
  sl.registerLazySingleton(() => DestinationRepo());
  sl.registerLazySingleton(() => DriverAppOnBoardingRepo());
  sl.registerLazySingleton(() => DriverAppHomeRepo());
  sl.registerLazySingleton(() => HistoryRepo());
  sl.registerLazySingleton(() => NotificationRepo());
  sl.registerLazySingleton(() => WalletRepo());
  sl.registerLazySingleton(() => DatingAppOnBoardingRepo());
  sl.registerLazySingleton(() => ChoiceRepo());
  sl.registerLazySingleton(() => DatingAppHomeRepo());
  sl.registerLazySingleton(() => DatingAppUserRepo());
  sl.registerLazySingleton(() => DatingAppChatRepo());
  sl.registerLazySingleton(() => HouseHomeRepo());
  sl.registerLazySingleton(() => HouseNotificationRepo());
  sl.registerLazySingleton(() => ServiceRepo());
  sl.registerLazySingleton(() => CourseRepo());
  sl.registerLazySingleton(() => AcademyWishListRepo());
  sl.registerLazySingleton(() => AcademyPaymentRepo());
  sl.registerLazySingleton(() => AcademyDesignRepo());
  sl.registerLazySingleton(() => DattingAppNotificationRepo());
  sl.registerLazySingleton(() => DatingAppProfileRepo());
  sl.registerLazySingleton(() => DriverAppPaymentRepo());
  sl.registerLazySingleton(() => DriverAppHistoryRepo());
  sl.registerLazySingleton(() => DriverAppNotificationRepo());
  sl.registerLazySingleton(() => SixCategoryRepo());
  sl.registerLazySingleton(() => SixMegaDealRepo());
  sl.registerLazySingleton(() => SixBrandRepo());
  sl.registerLazySingleton(() => SixProductRepo());
  sl.registerLazySingleton(() => SixBannerRepo());
  sl.registerLazySingleton(() => SixOnBoardingRepo());
  sl.registerLazySingleton(() => SixAuthRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => SixProductDetailsRepo());
  sl.registerLazySingleton(() => SixSearchRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => SixOrderRepo());
  sl.registerLazySingleton(() => SixSellerRepo());
  sl.registerLazySingleton(() => SixCouponRepo());
  sl.registerLazySingleton(() => SixChatRepo());
  sl.registerLazySingleton(() => SixNotificationRepo());
  sl.registerLazySingleton(() => SixProfileRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => SixWishListRepo());
  sl.registerLazySingleton(() => SixCartRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => SixSplashRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => SixSupportTicketRepo());
  sl.registerLazySingleton(() => SixTrackingRepo());
  sl.registerLazySingleton(() => RestCategoryRepo());
  sl.registerLazySingleton(() => RestBannerRepo());
  sl.registerLazySingleton(() => RestProductRepo());
  sl.registerLazySingleton(() => RestLanguageRepo());
  sl.registerLazySingleton(() => RestOnBoardingRepo());
  sl.registerLazySingleton(() => RestCartRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => RestOrderRepo());
  sl.registerLazySingleton(() => RestChatRepo());
  sl.registerLazySingleton(() => RestLocationRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => RestSetMenuRepo());
  sl.registerLazySingleton(() => RestProfileRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => RestSearchRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => RestNotificationRepo());
  sl.registerLazySingleton(() => RestCouponRepo());
  sl.registerLazySingleton(() => RestWishListRepo());
  sl.registerLazySingleton(() => RestaurantDeliveryBoySplashRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => RestaurantDeliveryBoyLanguageRepo());
  sl.registerLazySingleton(() => RestaurantDeliveryBoyAuthRepo(sharedPreferences: sl()));
  sl.registerLazySingleton(() => RestaurantDeliveryBoyProfileRepo( sharedPreferences: sl()));
  sl.registerLazySingleton(() => RestaurantDeliveryBoyOrderRepo( sharedPreferences: sl()));


  // Provider
  sl.registerFactory(() => MainProvider());
  sl.registerFactory(() => OnBoardingProvider(onBoardingRepo: sl()));
  sl.registerFactory(() => OnboardingProvider(onboardingRepo: sl()));
  sl.registerFactory(() => AuthProvider(authRepo: sl()));
  sl.registerFactory(() => ProfileProvider(profileRepo: sl()));
  sl.registerFactory(() => MembershipProvider(membershipRepo: sl()));
  sl.registerFactory(() => ChatProvider(chatRepo: sl()));
  sl.registerFactory(() => ContactProvider(contactRepo: sl()));
  sl.registerFactory(() => FaqProvider(faqRepo: sl()));
  sl.registerFactory(() => CharityProvider(charityRepo: sl()));
  sl.registerFactory(() => OrganizationProvider(organizationRepo: sl()));
  sl.registerFactory(() => GiftProvider(giftRepo: sl()));
  sl.registerFactory(() => GoalsProvider(goalsRepo: sl()));
  sl.registerFactory(() => StepProvider(stepRepo: sl()));
  sl.registerFactory(() => PromoProvider(promoRepo: sl()));
  sl.registerFactory(() => AppointmentProvider(appointmentRepo: sl()));
  sl.registerFactory(() => HomeProvider());
  sl.registerFactory(() => ChooseCategoryProvider(categoryRepo: sl()));
  sl.registerFactory(() => GroceryHomeProvider(homeRepo: sl()));
  sl.registerFactory(() => ProductProvider());
  sl.registerFactory(() => SearchProvider(searchRepo: sl(),homeRepo: sl()));
  sl.registerFactory(() => BranchProvider(branchRepo: sl()));
  sl.registerFactory(() => CartProvider(cartRepo: sl()));
  sl.registerFactory(() => CheckoutProvider(checkoutRepo: sl()));
  sl.registerFactory(() => FavouriteProvider(favouriteRepo: sl()));
  sl.registerFactory(() => PaymentProvider(paymentRepo: sl()));
  sl.registerFactory(() => ScreensAuthProvider());
  sl.registerFactory(() => RideShareOnBoardingProvider(rideShareOnBoardingRepo: sl()));
  sl.registerFactory(() => RideShareHomeProvider(rideShareHomeRepo: sl()));
  sl.registerFactory(() => RideShareDestinationProvider(destinationRepo: sl()));
  sl.registerFactory(() => RideShareAuthProvider());
  sl.registerFactory(() => DriveAppOnBoardingProvider(driverAppOnBoardingRepo: sl()));
  sl.registerFactory(() => DriverAppHomeProvider(driverAppHomeRepo: sl()));
  sl.registerFactory(() => DriverAppAuthProvider());
  sl.registerFactory(() => HistoryProvider(historyRepo: sl()));
  sl.registerFactory(() => NotificationProvider(notificationRepo: sl()));
  sl.registerFactory(() => WalletProvider(walletRepo: sl()));
  sl.registerFactory(() => DestinationProvider(destinationRepo: sl()));
  sl.registerFactory(() => DatingAppOnBoardingProvider(onBoardingRepo: sl()));
  sl.registerFactory(() => ChoiceProvider(choiceRepo: sl()));
  sl.registerFactory(() => DatingAppHomeProvider(homeRepo: sl()));
  sl.registerFactory(() => DatingAppUserProvider(datingAppUserRepo: sl()));
  sl.registerFactory(() => DatingAppChatProvider(datingAppChatRepo: sl()));
  sl.registerFactory(() => HouseHomeProvider(homeRepo: sl()));
  sl.registerFactory(() => HouseNotificationProvider(notificationRepo: sl()));
  sl.registerFactory(() => HouseCartProvider());
  sl.registerFactory(() => ServiceProvider(serviceRepo: sl()));
  sl.registerFactory(() => CourseProvider(courseRepo: sl()));
  sl.registerFactory(() => AcademyWishListProvider(wishListRepo: sl()));
  sl.registerFactory(() => AcademyPaymentProvider(paymentRepo: sl()));
  sl.registerFactory(() => AcademyDesignProvider(designRepo: sl()));
  sl.registerFactory(() => DattingAppNotificationProvider(notificationRepo: sl()));
  sl.registerFactory(() => DatingAppProfileProvider(profileRepo: sl()));
  sl.registerFactory(() => DriverAppPaymentProvider(paymentRepo: sl()));
  sl.registerFactory(() => DriverAppHistoryProvider(historyRepo: sl()));
  sl.registerFactory(() => DriverAppNotificationProvider(notificationRepo: sl()));
  sl.registerFactory(() => SixCategoryProvider(categoryRepo: sl()));
  sl.registerFactory(() => SixMegaDealProvider(megaDealRepo: sl()));
  sl.registerFactory(() => SixBrandProvider(brandRepo: sl()));
  sl.registerFactory(() => SixProductProvider(productRepo: sl()));
  sl.registerFactory(() => SixBannerProvider(bannerRepo: sl()));
  sl.registerFactory(() => SixOnBoardingProvider(onboardingRepo: sl()));
  sl.registerFactory(() => SixAuthProvider(authRepo: sl()));
  sl.registerFactory(() => SixProductDetailsProvider(productDetailsRepo: sl()));
  sl.registerFactory(() => SixSearchProvider(searchRepo: sl()));
  sl.registerFactory(() => SixOrderProvider(orderRepo: sl()));
  sl.registerFactory(() => SixSellerProvider(sellerRepo: sl()));
  sl.registerFactory(() => SixCouponProvider(couponRepo: sl()));
  sl.registerFactory(() => SixChatProvider(chatRepo: sl()));
  sl.registerFactory(() => SixNotificationProvider(notificationRepo: sl()));
  sl.registerFactory(() => SixProfileProvider(profileRepo: sl()));
  sl.registerFactory(() => SixWishListProvider(wishListRepo: sl()));
  sl.registerFactory(() => SixSplashProvider(splashRepo: sl()));
  sl.registerFactory(() => SixCartProvider(cartRepo: sl()));
  sl.registerFactory(() => SixSupportTicketProvider(supportTicketRepo: sl()));
  sl.registerFactory(() => SixTrackingProvider(trackingRepo: sl()));
  sl.registerFactory(() => SixThemeProvider(sharedPreferences: sl()));
  sl.registerFactory(() => SixLocalizationProvider(sharedPreferences: sl()));

  sl.registerFactory(() => RestThemeProvider(sharedPreferences: sl()));
  sl.registerFactory(() => RestLocalizationProvider(sharedPreferences: sl()));
  sl.registerFactory(() => RestLanguageProvider(languageRepo: sl()));
  sl.registerFactory(() => RestOnBoardingProvider(onboardingRepo: sl()));
  sl.registerFactory(() => RestCategoryProvider(categoryRepo: sl()));
  sl.registerFactory(() => RestBannerProvider(bannerRepo: sl()));
  sl.registerFactory(() => RestProductProvider(productRepo: sl()));
  sl.registerFactory(() => RestCartProvider(cartRepo: sl()));
  sl.registerFactory(() => RestOrderProvider(orderRepo: sl()));
  sl.registerFactory(() => RestChatProvider(chatRepo: sl()));
  sl.registerFactory(() => RestAuthProvider());
  sl.registerFactory(() => RestLocationProvider(sharedPreferences: sl(), locationRepo: sl()));
  sl.registerFactory(() => RestProfileProvider(profileRepo: sl()));
  sl.registerFactory(() => RestNotificationProvider(notificationRepo: sl()));
  sl.registerFactory(() => RestSetMenuProvider(setMenuRepo: sl()));
  sl.registerFactory(() => RestWishListProvider(wishListRepo: sl(), productRepo: sl()));
  sl.registerFactory(() => RestCouponProvider(couponRepo: sl()));
  sl.registerFactory(() => RestSearchProvider(searchRepo: sl()));

  sl.registerFactory(() => RestaurantDeliveryBoyThemeProvider(sharedPreferences: sl()));
  sl.registerFactory(() => RestaurantDeliveryBoySplashProvider(splashRepo: sl()));
  sl.registerFactory(() => RestaurantDeliveryBoyLocalizationProvider(sharedPreferences: sl()));
  sl.registerFactory(() => RestaurantDeliveryBoyLanguageProvider(languageRepo: sl()));
  sl.registerFactory(() => RestaurantDeliveryBoyAuthProvider(authRepo: sl()));
  sl.registerFactory(() => RestaurantDeliveryBoyProfileProvider(profileRepo: sl()));
  sl.registerFactory(() => RestaurantDeliveryBoyOrderProvider(orderRepo: sl()));
  sl.registerFactory(() => RestaurantDeliveryBoyLocationProvider(sharedPreferences: sl()));

  // External
  final sharedPreferences = await SharedPreferences.getInstance();
  sl.registerLazySingleton(() => sharedPreferences);
  sl.registerLazySingleton(() => Dio());
  sl.registerLazySingleton(() => LoggingInterceptor());
  sl.registerLazySingleton(() => DataConnectionChecker());

}
